### ISSUE TITLE
Cannot install module

### ISSUE THREAD

**Issue by jaykobi** [brandung/magento2-gelf-logger#1]
Hi, when I try to install the module I get an error:

`Interface 'Gelf\Transport\TransportInterface' not found in /var/www/magento/app/code/Brandung/GelfLogger/Model/ConfiguredUdpTransport.php on line 11`

Are some files missing in this repo? The folder Transport does not exist.

**Comment by davidverholen** [comment]
@jaykobi did you install it using composer? It seems that you are missing the dependency:
https://github.com/brandung/magento2-gelf-logger/blob/master/composer.json#L7

**Comment by jaykobi** [comment]
No, I didn't :) Thank you!
